// Mayim — Tigrinya Proverbs (ምስላ) Word Bank
// Each entry: { tigrinya (Ge'ez script), latin (romanisation), english (meaning), difficulty }
// difficulty is auto-tagged: 'easy' = 3–4 words, 'medium' = 5–6 words, 'hard' = 7+ words

const PROVERBS = [

  // ── Easy (3–4 words — show first 2, mask last 1) ──────────────────────────
  {
    tigrinya:   'ፍቕሪ ዕዉር ኢዩ',
    latin:      'Fiqri iwur iyu',
    english:    'Love is blind',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ሓቂ ጸሓይ ኢያ',
    latin:      'Haqi tsehay iya',
    english:    'Truth is the sun',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ሰላም ዓቢ ሃብቲ',
    latin:      'Selam abi habti',
    english:    'Peace is great wealth',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ሓዳር ዓቢ ሕይወት',
    latin:      'Hadar abi hywet',
    english:    'Family is great life',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ሰናይ ቃል ልቢ ይኽፍት',
    latin:      'Senay qal libi ykheft',
    english:    'A kind word opens the heart',
    difficulty: 'easy',
  },

  // ── Medium (5–6 words — show first 50%, mask rest) ────────────────────────
  {
    tigrinya:   'ዝሰርሐ ኢዱ ዘይሓስር',
    latin:      'Zserihe idu zeyhaser',
    english:    'He who works does not lose his hand',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ብዙሕ ኢድ ዕዮ ቀሊሉ',
    latin:      'Bzuh id eyo qelilu',
    english:    'Many hands make work easy',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ሕጊ ዘይፈልጥ ንጹህ ኣይኮነን',
    latin:      'Hgi zeyfeltsi ntsuH aykonenj',
    english:    'One who does not know the law is not innocent',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ናብ ሃገሩ ዝኸደ ዘይጠፍእ',
    latin:      'Nab hageru zkede zeytfei',
    english:    'One who goes to their homeland does not get lost',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ቀዳም ዝዘርኤ ሰንበት ይሕፍስ',
    latin:      'Qedam zzerie senbet yhifs',
    english:    'What is sown on Saturday is harvested on Sunday',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ሓሶት ዓቢ ጸላኢ ሰብ',
    latin:      'Hasot abi tsielai seb',
    english:    'A lie is a person\'s greatest enemy',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ሰብ ዘይፈልጦ ሰብ ኣይፈልጦን',
    latin:      'Seb zeyfelho seb ayfelhonn',
    english:    'One who does not know others is not known by others',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ምቕዋም ዘሎ ሰብ ኣይወድቕን',
    latin:      'Miqwam zelo seb aywediqn',
    english:    'A person who has balance does not fall',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ዝኸፈተ ኣፍ ዝሓዘ ሎሚ',
    latin:      'Zkefete af zhaze lomi',
    english:    'The mouth that opened holds something today',
    difficulty: 'medium',
  },

  // ── Hard (7+ words — show first 50%, mask rest) ────────────────────────────
  {
    tigrinya:   'ሓቂ ጸሓይ ከም ዘይትኽወል ይፍለጥ',
    latin:      'Haqi tsehay kem zeytkhewel yfeltet',
    english:    'Truth is known like the sun that cannot be hidden',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ዝበልዐ ዘይስዓር ዝደቀሰ ዘይሰኣን',
    latin:      'Zbelia zeysiar zdiqese zeysian',
    english:    'What is eaten is not wasted, what is slept is not missed',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ሕሱም ሰብ ናብ ጽቡቕ ቦታ ኣይኸድን',
    latin:      'Hsum seb nab tsbuk bota aykedn',
    english:    'A wicked person does not go to a good place',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ኣብ ዝዓበኻ ዓዲ ሕማቕ ሰብ ኣይትኸን',
    latin:      'Ab zdabeka adi hmaq seb aytken',
    english:    'Do not be a bad person in the village where you grew up',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ብጾት ዘይብሉ ሰብ ዛፍ ዘይብሉ ሜዳ',
    latin:      'Btsot zeyblu seb zaf zeyblu meda',
    english:    'A person without friends is a field without trees',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ዝኸደ ዝሓደሮ ዝቐነዮ ዝሓዘሎ',
    latin:      'Zkede zhadero zqeneyo zhazelo',
    english:    'Where one goes they stay, where one rests they remain',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ሰብ ናብ ሰቡ ዝተመልሰ ጠፊኡ ኣይኮነን',
    latin:      'Seb nab sebu ztemelse tefiu aykonenj',
    english:    'A person who returns to their people is not lost',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ብዘይ ምምሃር ዕቤት ዘሎ ምስምስ ኣይኮነን',
    latin:      'Bzeyi mmehar ibiet zelo msmss aykonenj',
    english:    'Growth without learning is merely an excuse',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ጸጋ ዝኸፍሎ ምቕዳም ዝሓትቶ ትሕትና',
    latin:      'Tsega zkeflo miqdam zhato tihtna',
    english:    'Fortune demands diligence, then asks for humility',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ኣብ ቤት ዝፈሰሰ ናብ ሃገር ዘይፈስስ',
    latin:      'Ab bet zfesse nab hager zeyfess',
    english:    'What is poured in the house does not flow to the nation',
    difficulty: 'hard',
  },
  {
    tigrinya:   'እዛ ሕጂ ዝኽፈታ ዓወት ጽባሕ ዝዝከር',
    latin:      'Iza hji zkefeta awet tsbah zzkr',
    english:    'The victory opened today is remembered tomorrow',
    difficulty: 'hard',
  },

  // ── Easy additions ──────────────────────────────────────────────────────────
  {
    tigrinya:   'ቀምሽ ኣደይ አሐንኲሉኒ',
    latin:      'Q\'emish adey ahenkwiluni',
    english:    'My mother\'s dress tripped me',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ቀረባ ሓውካ ገንዘብካ',
    latin:      'Q\'ereba hawikha genzebkha',
    english:    'Your close brother is your money',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ቁሓሚዮ ተበልኩዋስ ትጎስሞ',
    latin:      'Q\'uhamiyo tebelkuwas tigosmo',
    english:    'When I told her to crunch it, she swallowed it whole',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ቃል ህዝቢ፡ ቃል እዝጊ',
    latin:      'Q\'al hizbi, q\'al izgi',
    english:    'The voice of the people is the voice of God',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ቆልዓ ብንኡሱ፡ ቊርበት ብርሑሱ',
    latin:      'Q\'ol\'a bini\'isu, q\'urbet birhusu',
    english:    'A child when young; a hide when wet',
    difficulty: 'easy',
  },
  {
    tigrinya:   'በትሪ ሓቂ ትቀጥን\'ምበር ኣይትስበርን',
    latin:      'Betri haq\'i tiq\'et\'in\'imber ayitisberin',
    english:    'The staff of truth may thin, but it does not break',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ብላዕ ንኸርስኻ፡ ፍረድ ንነብስኻ',
    latin:      'Bila\'e nikherisikha, fired ninebsikha',
    english:    'Eat for your stomach; judge for yourself',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ብልዒ ሓላፊ፡ ሽም ተራፊ',
    latin:      'Bili\'i halafi, shim terafi',
    english:    'Food passes; a name remains',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ብዘሎካ ተወከፍ ብዘይብልካ ኣይትሰከፍ',
    latin:      'Bizelokha tewekef bizeybilkha aytisekef',
    english:    'Rely on what you have; do not worry about what you don\'t',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ብዘመነይ ይጥዓሞ ወገነይ',
    latin:      'Bizemeney yit\'amo wegeney',
    english:    'May my people prosper in my time',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ተሃዊኸን ይኽዕወኦ፡ ተደቢረን ይሓፍሰኦ',
    latin:      'Tehawikhen yikh\'iwe\'o, tedebiren yihafse\'o',
    english:    'In haste they spill it; with patience they gather it',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ተቓሊሱ ዘይኽእል ቃልሲ ኣይፍቶ',
    latin:      'Teq\'alisu zeyki\'il q\'alsi ayfito',
    english:    'Let one who cannot fight not love the struggle',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ነዲኣ ገዲፋስ፡ ሓትናኣ ትናፍቕ',
    latin:      'Nedi\'a gedifas, hatina\'a tinafiq\'',
    english:    'She leaves her mother and longs for her aunt',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ንለባም ኣምተሉ፡ ንዓሻ ዶርጉሓሉ',
    latin:      'Nilebam amtelu, ni\'asha dorguhalu',
    english:    'Give a hint to the wise; pour it out for the fool',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ንዘይትገድፈኒ ኣይተካላብተኒ',
    latin:      'Nizeytigidfeni aytekalabteni',
    english:    'Since you won\'t leave me, do not harass me',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ኣብ ኲናት ዘይወዓለ በሊሕ',
    latin:      'Ab kwinat zeywi\'ale belih',
    english:    'He who has not been in war is sharp-tongued',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ኣይትብከ እንዲዩ ዘብክየኒ ዘሎ',
    latin:      'Aytibke indiyu zebkiyeni zelo',
    english:    'It is the "don\'t cry" that is making me cry',
    difficulty: 'easy',
  },
  {
    tigrinya:   'እሾኽ እሾኽ\'ያ ተውጽኣ',
    latin:      'Ishokh ishokh\'ya tewts\'a',
    english:    'A thorn is removed by a thorn',
    difficulty: 'easy',
  },
  {
    tigrinya:   'እንተዘይተበትኸስ ጽቡቕ ቅጥኒ',
    latin:      'Entezeytebetkhes ts\'ibuq\' q\'it\'ni',
    english:    'If it hasn\'t snapped, it\'s a fine thread',
    difficulty: 'easy',
  },
  {
    tigrinya:   'እዝኒ፡ መሰታ ቀዳሞት',
    latin:      'Izni, meseta q\'edamot',
    english:    'The ear, a peer of the ancients',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ከይቀተልካ ጐፈሬ፡ ከይኣረጋገጽካ ወሬ',
    latin:      'Keyq\'etelka gofere, keyeragetiska wore',
    english:    'A mane before killing; news before confirming',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ከይብሉኒ ዝብልስ፡ ከይተባህለ ዘይተርፍ',
    latin:      'Keybiluni zibils, keytebahle zeyterf',
    english:    'He who says "lest they speak of me" will surely be spoken of',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ከይተቐብኡ ኣይነግሱ፡ ከይመንኮሱ ኣይጵጵሱ',
    latin:      'Keyteq\'eb\'u aynegsu, keymenkosu ayipipsisu',
    english:    'They don\'t rule without being anointed; they don\'t become bishops without being monks',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ከይተዓደመ ዚመጸ፡ ከይጸገበ ወጸ',
    latin:      'Keyte\'ademe zimetse, keyts\'egebe witse',
    english:    'He who came uninvited left unsatisfied',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ከይኮነ ወግን፡ ከይተሰብረ ጸግን',
    latin:      'Keykhone wegin, keytesebre tsegn',
    english:    'Settle it before it happens; mend it before it breaks',
    difficulty: 'easy',
  },
  {
    tigrinya:   'ከይወዓሉ ይወዓዓሉ፡ ከይተኣማመኑ ይማሓሓሉ',
    latin:      'Keywi\'alu yiwi\'a\'alu, keyte\'amamenu yimahahalu',
    english:    'They make pacts without spending the day; they swear to each other without trusting',
    difficulty: 'easy',
  },

  // ── Medium additions ─────────────────────────────────────────────────────────
  {
    tigrinya:   'ቀቢሩ ዝምለስ ያኢ፡ ዝመውት ኣይመስሎን',
    latin:      'Q\'ebiru zimiles ya\'i, zimewit aymeslon',
    english:    'One who returns from burying someone acts as if he will never die',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ቃል ዓለም ክትገብሪ፡ ጾምኪ ከይትሓድሪ',
    latin:      'Q\'al alem kitgebri, tsomki keytihadri',
    english:    'Do not spend your fast fulfilling the world\'s word',
    difficulty: 'medium',
  },
  {
    tigrinya:   'በዓለገ ብመልሓሱ፡ ከልቢ ብጭራኡ ይልለ',
    latin:      'Be\'alege bimelhasu, kelbi bich\'ira\'u yille',
    english:    'A crude person is known by his tongue; a dog by its tail',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ባዕላ መቲራቶ ተሓንቀት፡ ባዕላ ሰትያቶ ተሰርነቐት',
    latin:      'Ba\'ila metirato tehanq\'et, ba\'ila setyato teserneq\'et',
    english:    'She cut it herself and choked; she drank it herself and it went down the wrong way',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ባዕላ ወሊዳቶ ኣይመሰለን፡ ባዕላ ሰንኪታቶ ኣይበሰለን',
    latin:      'Ba\'ila welidato aymeselen, ba\'ila senkitato aybeselen',
    english:    'She gave birth herself but didn\'t believe it; she kneaded it herself but it didn\'t bake',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ብዕራይ ናብ ዘበለ ተበለ፡ ዕርፊ ኣጽንዕ',
    latin:      'Bi\'iray nab zebele tebele, irfi atsn\'i\'e',
    english:    'Wherever the ox turns, hold the plough handle firm',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ተሓጓሚያ እንተሎስ፣ ትሓዝ ልቢ ይጠርጥ',
    latin:      'Tehaguamyia entelos, tihaz libi yitert\'',
    english:    'When a predator is near, the heart of the catch pounds',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ነገርያ ዘይጸገበስ ጓል ዋጣ ይሕጸ',
    latin:      'Negerya zeyts\'egebes gual wata yihitse',
    english:    'One who has not had enough trouble betroths a singer\'s daughter',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ናትካ ገዲፍካ ናይ ናይ እማትካ',
    latin:      'Natkha gedifka nay nay imatkha',
    english:    'Leaving yours for that of others',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ንኣድግኻ ኣይትርጋሕ፡ ንጐበዝካንከ ዕጥቕኻ ፍታሕ፡ ኣይበሃልን\'ዩ',
    latin:      'Ni\'adigkha aytirgah, nigobezkanke it\'iq\'kha fitah, aybehalin\'iyu',
    english:    'Do not kick your donkey, and do not tell your brave man to loosen his belt',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ንዓሻ መዓልቲ ኣንዋሕካሉ፣ ዕብዳን ወሰኽካሉ',
    latin:      'Ni\'asha me\'alti anwahkalu, ibdan wesekhkalu',
    english:    'If you lengthen the day for a fool, you increase his madness',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣሓ ኣብ ዘይወዓልኦ ኮባቡ',
    latin:      'Aha ab zeywi\'al\'o kobabu',
    english:    'Cow dung where the cows did not spend the day',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ጨጓርያ ከልቢስ፡ ኣሎ እናበልዎ ሞተ',
    latin:      'Ch\'eguarya kelbis, alo inabelwo mote',
    english:    'While they said the hairy dog was there, it died',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣብ ከብዲ ጽጉብሲ ጥሙይ የሎን',
    latin:      'Ab kebdi ts\'igubsi timuy yelon',
    english:    'In the stomach of the full, there is no hungry person',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣብ ክንደይ ርእሳ፡ መዲድ ይፈርሳ',
    latin:      'Ab kindey ri\'isa, medid yifersa',
    english:    'On how many heads does the millstone break?',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣነን ሓጺሩኒ እብል ንሱን ተደቢሩ ይስዕስዕ',
    latin:      'Anen hats\'iruni ibil nisun tedebira yisis\'i',
    english:    'I say it is too short for me, yet he dances with a leap',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣንስቲ ኣይለምና፡ እንተ ለመና ኸኣ፡ ኣይስኣና',
    latin:      'Anisti aylemna, ente lemena khe\'a, ayis\'ana',
    english:    'Women do not beg; but if they do, they do not lack',
    difficulty: 'medium',
  },
  {
    tigrinya:   'አንጭዋ ደገስ ንአንጭዋ ገዛ ተውጽኣ',
    latin:      'Anch\'wa deges nianch\'wa geza tewts\'a',
    english:    'The outside mouse drives out the house mouse',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣያ ዘለዎ ዝበክስ፡ ንአያ ዘይብሉ ከብኪ',
    latin:      'Aya zelewo zibekis, ni\'aya zeybilu kebki',
    english:    'He who has an elder brother cries; he who has none endures',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ኣይረኣኹን ኣይሰማዕኩን ሓንቲ፡ ሪኤ ሰሚዔ ብዝሕቲ',
    latin:      'Ayre\'akhun aysima\'khun hanti, ri\'ie simi\'ie bizhti',
    english:    '"I didn\'t see, I didn\'t hear" is one; "I saw and heard" are many',
    difficulty: 'medium',
  },
  {
    tigrinya:   'እናኸኣሎ ከሎ ዘይገብር፡ ክጥዓስ ይነብር',
    latin:      'Inakhe\'alo kelo zeygebir, kiti\'as yinebir',
    english:    'He who does not do it while he can lives in regret',
    difficulty: 'medium',
  },
  {
    tigrinya:   'እንካ ዘይፈልጥ፡ ሃባ መን ኣልመዶ',
    latin:      'Inka zeyfelit, haba men almedo',
    english:    'Who taught "give" to one who doesn\'t know "take"?',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከልቢ ዝበልዖ ስጋ\'ምበር ዝተኣልሞ በትሪ ዘይርኢ',
    latin:      'Kelbi zibeli\'o sig\'imber, zite\'almo betri zeyri\'i',
    english:    'A dog sees the meat it eats, not the staff aimed at it',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከመ\'ሎኻ አይትበሎ፡ ኣብ ገጹ ኣስተብህሎ',
    latin:      'Keme\'lokha ayitibelo, ab getsu astebhilo',
    english:    'Do not ask "how are you?"; observe his face',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከም ቀደም ይመስለክን፡ ውሕጅ ይወስደክን',
    latin:      'Kem q\'edem yimeslekin, wihij yiwisdekin',
    english:    'You think it\'s like before, until the flood takes you',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከም ዝፈትወኒ ይስዕመኒ፡ ከም ዝጸልኣኒ ይወቕዓኒ',
    latin:      'Kem zifetweni yisu\'imeni, kem zits\'el\'ani yiwiq\'ani',
    english:    'He kisses me as one who loves me; he strikes me as one who hates me',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከብዲ ከም ዘልመድካዮ፡ ሕልሚ ከም ዝፈታሕካዮ',
    latin:      'Kebdi kem zelmedkayo, hilmi kem zifetakhkayo',
    english:    'The stomach is as you train it; a dream is as you interpret it',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከብድኻ ሓምሊ ምልኣዮ፡ ዝባንካ ወደ\'ቦ ኣይርኣዮ',
    latin:      'Kebdikha hamli mil\'ayo, zibanka wede\'abo ayri\'ayo',
    english:    'Fill your stomach with greens; let your back not be seen by your kinsman',
    difficulty: 'medium',
  },
  {
    tigrinya:   'ከይሓረዱ ሓዊ አንደዱ፡ ከይጸመዱ ኣንጐዱ',
    latin:      'Keyharedu hawi andedu, keyts\'emedu angodu',
    english:    'They lit the fire before slaughtering; they moved the grain before yoking',
    difficulty: 'medium',
  },

  // ── Hard additions ───────────────────────────────────────────────────────────
  {
    tigrinya:   'ቀሺ ዝበለካ ግበር፡ ቀሺ ዝገበሮ ኣይትግበር',
    latin:      'Q\'eshi zibelekha giber, q\'eshi zigibero aytigber',
    english:    'Do what the priest tells you, but do not do what the priest does',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ቀቅድሚ ሃገራ ዝወለደት መሸላ ወይ ንዒፍ ወይ ንወንጭፍ',
    latin:      'Q\'eq\'dimi hagera ziweledet meshela wey ni\'if wey niwenchif',
    english:    'Sorghum that ripens before its season is for birds or the sling',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ቀታሊ ሰብኣይኪ፡ ተቐታሊ ሓውኪ፡ ዘይሩ ዘይሩ ሓዘኑስ ናትኪ',
    latin:      'Q\'etali seb\'ayki, teq\'etali hawiki, zeyru zeyru hazenus natki',
    english:    'The killer of your husband, the slain your brother; either way, the grief is yours',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ቀናፍዝዶ መፋልስ ይሕሻ? ኩለን ወዳእቲ እኽሊ ይለሓሳ',
    latin:      'Q\'enafizdo mefals yihisha? Kulen weda\'ti ikhli yilehasa',
    english:    'Are hedgehogs better than porcupines? They all lick the grain until it\'s gone',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ቁሪ ናበይ ደሊኻ ናብ ክዱናት፡ እቶም ዕሩቓት\'ከ ንሶም ደኣ ትሑዛት',
    latin:      'Q\'uri nabey delikha nab kidunat etom iruq\'at\'ke nisom de\'a tihuzat',
    english:    'Cold, where are you going? To the clothed. And the naked? They are already possessed',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ቂም ሒዝካ ጸሎት፡ ቁም ነገር ሒዝካ ተረት',
    latin:      'Q\'im hizka tselot, q\'um neger hizka teret',
    english:    'Prayer with a grudge; a proverb with no substance',
    difficulty: 'hard',
  },
  {
    tigrinya:   'በዓለገ ኣይትበል ዕጥንጥን፡ ወዲ ጭዋ ቀጢኑ አይቀጥን',
    latin:      'Be\'alege aytibel it\'init\'in, wedi ch\'iwa q\'et\'inu ayq\'et\'in',
    english:    'Crude one, do not be arrogant; a noble\'s son remains noble even if thin',
    difficulty: 'hard',
  },
  {
    tigrinya:   'በይኑ ዝጐዪ ዝቕድሞ የብሉ፡ በይኑ ዝምጉት ዝረትዖ የብሉ',
    latin:      'Beynu zigoyi ziq\'idmo yeblu, beynu zimugut ziret\'o yeblu',
    english:    'He who runs alone has no one to lead him; he who argues alone has no one to defeat him',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ባዕሉ ዝኣመነ ምስክር ኣየድሊ፡ ብሱሩ ዝመንመነ ምሳር ኣየድሊ',
    latin:      'Ba\'ilu zi\'amene misikir ayedli, bisuru zimenmene misar ayedli',
    english:    'One who confesses needs no witness; wood rotten at the root needs no axe',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ተሓሳሚ ጓሳስ ምስሑ ዚተሓስበ ድራሩ ይዀኖ',
    latin:      'Tehasami guasas mishu zitehasibe diraru yikhono',
    english:    'For a stingy shepherd, what was intended for lunch becomes his dinner',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ተጽግበኒ ቅጫ ኣብ መቕሎኣ ከላ ይፈልጣ',
    latin:      'Tets\'igibeni q\'icha ab meq\'lo\'a kela yifelit\'a',
    english:    'I know the bread that will satisfy me while it is still on the griddle',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ኣብ ርእሲ ልበይ እንተ ዝምዕደኒ፡ ክንደይ ደስ ምበለኒ',
    latin:      'Ab ri\'isi libey ente zim\'ideni, kindey des mibeleni',
    english:    'If he would advise me upon my heart, how happy I would be',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ኣብ ርእሲ ዋጣ ዘውጠጢ፡ ኣይክዋጥን እንትርፎ ከውጠጢ',
    latin:      'Ab ri\'isi wata zewt\'et\'i, aykiwat\'in intirfo kewt\'et\'i',
    english:    'On top of the singer\'s whining, he won\'t sing except to whine more',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ኣቦይ ቀሽ ዝበልዕዎ ሕምቶስ፥ ኣደይ ኢታይ ፈርሲ የጒስዔን',
    latin:      'Aboy q\'esh zibeli\'wo himtos, adey itay fersi yigwisi\'en',
    english:    'The bran my priest father ate makes my mother belch out dung',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ንዝጸገበ ብላዕ ኣይትበሎ፡ ንዝፈርሐ ትባዕ ኣይትበሎ',
    latin:      'Nizits\'egebe bila\'e aytibelo, niziferhe tiba\'e aytibelo',
    english:    'Do not tell a full person to eat; do not tell a frightened person to be brave',
    difficulty: 'hard',
  },
  {
    tigrinya:   'እምኒ ዝረገጸ ኣሰር የብሉ፡ ማይ ዝሰተየ ጨና የብሉ',
    latin:      'Imni ziregetse aser yeblu, may zisiteye ch\'ena yeblu',
    english:    'He who treads on stone leaves no footprint; he who drinks water has no scent',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ከይተሓርደ ኣይርከብ ስብሑ፡ ከይመርመርካ ኣይፍለጥ ጉርሑ',
    latin:      'Keyteharde ayrikeb sibhu, keymermerka ayfilet gurhu',
    english:    'Its fat isn\'t found until slaughtered; his secret isn\'t known until examined',
    difficulty: 'hard',
  },
  {
    tigrinya:   'ከይመኸርካ ዝግበር ከየብኳዕካ ዝጋገር፡ እቲ ይገፍሕ እቲ ይነፍሕ',
    latin:      'Keymekherka zigebir, keyebkw\'akha zigager, eti yigefih, eti yinefih',
    english:    'What is done without counsel, what is baked without leaven: one widens, the other puffs up',
    difficulty: 'hard',
  },

];
