// Mayim — Tigrinya Word Bank
// Each entry: { word (Ge'ez script), latin (romanisation), english (meaning), category }
// Add your own words below — the game uses all entries by default.

const WORDS = [
  // ── Food ──────────────────────────────────────────────────────────────────
  { word: "እንጀራ",    latin: "Injera",     english: "Sourdough flatbread",         category: "Food" },
  { word: "ጽብሒ",     latin: "Tsebhi",     english: "Spicy stew",                  category: "Food" },
  { word: "ቆሎ",      latin: "Kolo",       english: "Roasted barley snack",        category: "Food" },
  { word: "ሂምባሻ",    latin: "Himbasha",   english: "Celebration bread",           category: "Food" },
  { word: "ሽሮ",      latin: "Shiro",      english: "Chickpea flour stew",         category: "Food" },
  { word: "ቃርሳ",     latin: "Qarsa",      english: "Fresh butter",                category: "Food" },
  { word: "ቅንጬ",     latin: "Kinche",     english: "Cracked wheat porridge",      category: "Food" },
  { word: "ቡን",      latin: "Bun",        english: "Coffee",                      category: "Food" },
  { word: "ሻሂ",      latin: "Shahi",      english: "Tea",                         category: "Food" },
  { word: "ማይ",      latin: "May",        english: "Water",                       category: "Food" },
  { word: "ጸባ",      latin: "Tseba",      english: "Milk",                        category: "Food" },
  { word: "ቢራ",      latin: "Bira",       english: "Beer",                        category: "Food" },
  { word: "ዝግኒ",     latin: "Zigni",      english: "Spicy beef stew",             category: "Food" },
  { word: "ኣሊጫ",     latin: "Alicha",     english: "Mild vegetable stew",         category: "Food" },
  { word: "ጥብስ",     latin: "Tibs",       english: "Sautéed meat",               category: "Food" },
  { word: "ዳቦ",      latin: "Dabo",       english: "Bread",                       category: "Food" },
  { word: "መዓር",     latin: "Me'ar",      english: "Honey",                       category: "Food" },
  { word: "ሓምሊ",     latin: "Hamli",      english: "Collard greens",              category: "Food" },
  { word: "ትምቲሞ",    latin: "Timtimo",    english: "Red lentil stew",             category: "Food" },
  { word: "ፊንጃል",    latin: "Finjal",     english: "Small coffee cup",            category: "Food" },

  // ── Culture ───────────────────────────────────────────────────────────────
  { word: "መሰንቆ",    latin: "Masenqo",    english: "Single-stringed lute",        category: "Culture" },
  { word: "ክራር",     latin: "Kirar",      english: "Lyre-like instrument",        category: "Culture" },
  { word: "ዙረት",     latin: "Zuret",      english: "Traditional dance",           category: "Culture" },
  { word: "ዙርያ",     latin: "Zuria",      english: "Traditional dress",           category: "Culture" },
  { word: "ነጸላ",     latin: "Netsela",    english: "Traditional white shawl",     category: "Culture" },
  { word: "ኣውደዓመት",  latin: "Awde-amet",  english: "New Year / Holiday",          category: "Culture" },
  { word: "ጋሻ",      latin: "Gasha",      english: "Guest / Visitor",             category: "Culture" },
  { word: "ምርዓ",     latin: "Mir'a",      english: "Wedding ceremony",            category: "Culture" },
  { word: "ጥምቀት",    latin: "Timqet",     english: "Epiphany celebration",        category: "Culture" },
  { word: "መስቀል",    latin: "Mesqel",     english: "Finding of the True Cross",   category: "Culture" },
  { word: "ጅብና",     latin: "Jebena",     english: "Clay coffee pot",             category: "Culture" },
  { word: "መሶብ",     latin: "Mesob",      english: "Woven injera basket",         category: "Culture" },
  { word: "ጓይላ",     latin: "Guayla",     english: "Celebratory party / dance",   category: "Culture" },
  { word: "እልልታ",    latin: "Elelta",     english: "Ululation (joy call)",        category: "Culture" },
  { word: "ሽማግለ",    latin: "Shimagile",  english: "Community elder",             category: "Culture" },
  { word: "ባህሊ",     latin: "Bahli",      english: "Culture / Tradition",         category: "Culture" },
  { word: "ቋንቋ",     latin: "Quanqua",    english: "Language",                    category: "Culture" },
  { word: "ሃገር",     latin: "Hager",      english: "Country / Nation",            category: "Culture" },
  { word: "ሰላም",     latin: "Selam",      english: "Peace / Hello",               category: "Culture" },
  { word: "ፍቕሪ",     latin: "Fiqri",      english: "Love",                        category: "Culture" },

  // ── Daily Life ────────────────────────────────────────────────────────────
  { word: "መኪና",     latin: "Mekina",     english: "Car / Automobile",            category: "Daily Life" },
  { word: "ገዛ",      latin: "Geza",       english: "House / Home",                category: "Daily Life" },
  { word: "መንገዲ",    latin: "Mengedi",    english: "Road / Path",                 category: "Daily Life" },
  { word: "ዕዳጋ",     latin: "Edaga",      english: "Market / Bazaar",             category: "Daily Life" },
  { word: "ትምህርቲ",   latin: "Timhirti",   english: "Education / School",          category: "Daily Life" },
  { word: "ስራሕ",     latin: "Sirah",      english: "Work / Job",                  category: "Daily Life" },
  { word: "ገንዘብ",    latin: "Genzeb",     english: "Money",                       category: "Daily Life" },
  { word: "ቴሌፎን",    latin: "Telephon",   english: "Telephone",                   category: "Daily Life" },
  { word: "መጽሓፍ",    latin: "Mets'haf",   english: "Book",                        category: "Daily Life" },
  { word: "ደቂ",      latin: "Deqi",       english: "Children",                    category: "Daily Life" },
  { word: "ደቀባት",    latin: "Deqebat",    english: "Indigenous / Local people",   category: "Daily Life" },
  { word: "ጎረቤት",    latin: "Gorebet",    english: "Neighbour",                   category: "Daily Life" },
  { word: "ጸሓይ",     latin: "Tsehay",     english: "Sun",                         category: "Daily Life" },
  { word: "ወርሒ",     latin: "Werhi",      english: "Moon / Month",                category: "Daily Life" },
  { word: "ንፋስ",     latin: "Nifas",      english: "Wind / Breeze",               category: "Daily Life" },
  { word: "ክዳን",     latin: "Kidan",      english: "Clothes / Garment",           category: "Daily Life" },
  { word: "ጫማ",      latin: "Chama",      english: "Shoes",                       category: "Daily Life" },
  { word: "ደቂስካ",    latin: "Deqiska",    english: "Sleeping",                    category: "Daily Life" },
  { word: "ምሳሕ",     latin: "Misah",      english: "Lunch",                       category: "Daily Life" },
  { word: "ድራር",     latin: "Dirar",      english: "Dinner",                      category: "Daily Life" }
];
